import pandas
import matplotlib.pyplot as plt
df = pandas.read_csv('Datasets/metadata_clean_numeric.csv')

fig = plt.figure()
fig.subplots_adjust(hspace=0.5, wspace=1)
s1 = fig.add_subplot(3,4,1)
s1.title.set_text('director')
s1.set_xticklabels([])
s1.set_yticklabels([])
df['director_popularity'].plot.hist(bins=100)
s2 = fig.add_subplot(3,4,2)
s2.title.set_text('main_actor')
s2.set_xticklabels([])
s2.set_yticklabels([])
df['main_actor'].plot.hist(bins=100)
s3 = fig.add_subplot(3,4,3)
s3.title.set_text('secondary_actor')
s3.set_xticklabels([])
s3.set_yticklabels([])
df['secondary_actor'].plot.hist(bins=100)
s4 = fig.add_subplot(3,4,4)
s4.title.set_text('third_actor')
s4.set_xticklabels([])
s4.set_yticklabels([])
df['third_actor'].plot.hist(bins=100)
s5 = fig.add_subplot(3,4,5)
s5.title.set_text('duration')
s5.set_xticklabels([])
s5.set_yticklabels([])
df['duration'].plot.hist(bins=100)
s6 = fig.add_subplot(3,4,6)
s6.title.set_text('num_voted_users')
s6.set_xticklabels([])
s6.set_yticklabels([])
df['num_voted_users'].plot.hist(bins=100)
s7 = fig.add_subplot(3,4,7)
s7.title.set_text('keyword_1')
s7.set_xticklabels([])
s7.set_yticklabels([])
df['keyword_1'].plot.hist(bins=100)
s8 = fig.add_subplot(3,4,8)
s8.title.set_text('keyword_2')
s8.set_xticklabels([])
s8.set_yticklabels([])
df['keyword_2'].plot.hist(bins=100)
s9 = fig.add_subplot(3,4,9)
s9.title.set_text('keyword_3')
s9.set_xticklabels([])
s9.set_yticklabels([])
df['keyword_3'].plot.hist(bins=100)
s10 = fig.add_subplot(3,4,10)
s10.title.set_text('keyword_4')
s10.set_xticklabels([])
s10.set_yticklabels([])
df['keyword_4'].plot.hist(bins=100)
s11 = fig.add_subplot(3,4,11)
s11.title.set_text('keyword_5')
s11.set_xticklabels([])
s11.set_yticklabels([])
df['keyword_5'].plot.hist(bins=100)
#fig.tight_layout()
plt.savefig('normality.png')
#fig.show()
